name: rockhound
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - pooch>=0.5
    - xarray
    - pandas
    - rasterio
    - gdal<3.0.0
    - dask
    # Development requirements
    - matplotlib
    - cmocean
    - cartopy
    - pytest
    - pytest-cov
    - coverage
    - black
    - pylint
    - flake8
    - sphinx=1.8.5
    - sphinx_rtd_theme
    - sphinx-gallery
    - numpydoc
